FROM jenkins/jenkins:ltd

RUN apt-get -y update
RUN apt-get install -y pip

RUN cd /home
RUN mkdir alberto
RUN cd alberto

RUN git clone https://github.com/albertoggago/JobWeb

RUN pip install -r docker/requirements.txt

